

  // ===================== 奇趣探索（来自 coolexplore.com/zh） =====================
  {
    id: 'fun-web',
    name: '奇趣网站',
    desc: '脑洞、冷知识与新奇玩意',
    icon: 'smile',
    links: [
      { name: 'AvatarMaker', url: 'https://avatarmaker.com', desc: 'AvatarMaker是一款免费的在线卡' },
      { name: 'AutoDraw', url: 'https://www.autodraw.com', desc: '一个智能草图识别工具' },
      { name: 'Ping.pe', url: 'https://ping.pe', desc: '一个专业的网络诊断工具平台' },
      { name: 'SeedHub - 种子下载导航', url: 'https://www.seedhub.cc', desc: 'SeedHub是一个专注于种子资源导航的' },
      { name: 'This Waifu Does Not Exist', url: 'https://www.thiswaifudoesnotexist.net/', desc: '这是一个利用智能技术生成二次元动漫人物头' },
      { name: '雪花晶体研究网', url: 'http://www.snowcrystals.com', desc: '一个专业的雪花晶体研究网站' },
      { name: '金鱼直播：在线观赏舒缓减压的虚拟宠物', url: 'https://goldfishies.com', desc: 'Goldfishies.com是一个提供' },
      { name: 'Genact - 假装忙碌的终端模拟器', url: 'https://svenstaro.github.io/genact', desc: 'Genact是一个开源的终端活动模拟器' },
      { name: 'Windows 11 Web版 - 浏览器体验桌面系统', url: 'https://win11.blueedge.me', desc: '这是一个基于Web技术构建的Window' },
      { name: 'KeepTrack - 实时卫星追踪与太空数据平台', url: 'https://keeptrack.space/', desc: 'KeepTrack是一款专业的实时卫星追' },
      { name: 'Alltoall在线格式转换工具', url: 'https://www.alltoall.net/', desc: 'Alltoall是一个提供400+种格式' },
      { name: '答案之书 - 在线决策与灵感启发工具', url: 'https://proj.warmday.wang/answer', desc: '答案之书是一个基于传统实体书理念的在线互' },
      { name: '核武器爆炸模拟器 - NUKEMAP', url: 'https://nuclearsecrecy.com/nukemap', desc: 'NUKEMAP是一个交互式核爆炸模拟工具' },
      { name: 'Uchinoko Maker - 可爱卡通角色生成器', url: 'https://uchinoko-maker.jp', desc: 'Uchinoko Maker是一款日本开' },
      { name: '蒸汽波在线生成器 - 梦幻复古风格文字艺术工具', url: 'https://magiconch.com/vaporwave', desc: 'Magiconch蒸汽波生成器是一款专为' },
      { name: '黑客模拟器 - 在线模拟黑客编程界面', url: 'https://HackerTyper.com', desc: 'HackerTyper.com是一个趣味' },
      { name: 'Fact Slides - 有趣事实分享平台', url: 'http://www.factslides.com', desc: 'Fact Slides是一个收集全球各类' },
      { name: 'iPanda熊猫频道', url: 'https://www.ipanda.com', desc: 'iPanda熊猫频道是中国网络电视台（C' },
      { name: '产品坟墓 - 记录那些被淘汰的科技产品', url: 'http://productgraveyard.com', desc: '产品坟墓网站是一个记录各类已停止服务的数' },
      { name: 'ColorNames - 颜色命名与色彩灵感平台', url: 'https://colornames.org', desc: 'ColorNames是一个创新的颜色命名' },
      { name: 'Dialogue.moe', url: 'https://dialogue.moe', desc: 'Dialogue.moe是一个专注于动漫' },
      { name: 'GPT Online', url: 'https://gptonline.ai/', desc: 'GPT Online是一个免费的AI聊天' },
      { name: '机械图书馆', url: 'https://mechanical-library.org/', desc: '机械图书馆是一个专业的机械工程知识分享平' },
      { name: 'CityWalki', url: 'https://www.citywalki.com/', desc: '一个在线虚拟城市漫步体验平台' },
      { name: 'River Runner Global', url: 'https://river-runner-global.samlearner.com/', desc: '这是一个可视化追踪全球河流流向的地理工具' },
      { name: '极客模拟器 - 黑客风格打字模拟体验平台', url: 'https://geektyper.com', desc: 'GeekTyper提供逼真的黑客界面模拟' },
      { name: 'TV Garden', url: 'https://tv.garden/', desc: 'TV Garden是一个在线直播源收集和' },
      { name: '我爱工作 - 好玩的', url: 'https://ilove.works', desc: '我爱工作（ilove.works）是一个' },
      { name: '太空有多大', url: 'https://www.secaibi.com/howbigisspace/', desc: '一个通过滚动交互体验宇宙尺度的可视化项目' },
      { name: '广播迷', url: 'http://guangbomi.com/', desc: '广播迷是一个基于人工智能的在线广播平台' },
      { name: 'Grabient - 在线CSS渐变生成器', url: 'https://www.grabient.com', desc: 'Grabient是一款免费的在线CSS渐' },
      { name: 'Picrew', url: 'https://picrew.me', desc: 'Picrew是一个在线头像制作平台' },
      { name: 'Gridzzly - 自定义网格纸生成工具', url: 'https://www.gridzzly.com', desc: 'Gridzzly是一个免费的在线网格纸生' },
      { name: '护照指数 - 全球护照排名与免签查询工具', url: 'https://www.passportindex.org', desc: '护照指数是一个提供全球护照实时排名和免签' }
    ],
  },
  {
    id: 'web-game',
    name: '网页游戏',
    desc: '免下载，开浏览器即玩',
    icon: 'dice',
    links: [
      { name: 'Minecraft网页游戏', url: 'https://classic.minecraft.net', desc: '经典版Minecraft网页游戏' },
      { name: 'RA2Web - 红色警戒2在线游戏平台', url: 'https://ra2web.com', desc: '一个基于Web技术的红色警戒2游戏平台' },
      { name: 'GeoGuessr', url: 'http://geoguessr.com', desc: '一款基于谷歌街景的地理猜谜游戏' },
      { name: 'Lines FRVR', url: 'https://lines.frvr.com', desc: '一款基于HTML5的在线益智连线游戏' },
      { name: 'LoL Dodge Game', url: 'https://loldodgegame.com', desc: '英雄联盟技能躲避训练网站' },
      { name: 'Quick Draw', url: 'https://quickdraw.withgoogle.com/', desc: '一个由Google开发的智能涂鸦识别工具' },
      { name: 'Donitz的独立游戏发布平台', url: 'https://donitz.itch.io', desc: 'Donitz在itch.io上的个人页面' },
      { name: '小霸王游戏机 - 在线红白机FC游戏合集', url: 'https://www.yikm.net/', desc: '小霸王游戏机是一个提供在线FC红白机游戏' },
      { name: 'Play-CS - 在线反恐精英1.6游戏平台', url: 'https://play-cs.com', desc: 'Play-CS提供基于浏览器的经典反恐精' },
      { name: 'Twitch', url: 'https://www.twitch.tv/', desc: 'Twitch是全球领先的实时流媒体直播平' },
      { name: 'Wplace.live', url: 'https://wplace.live/', desc: '一个基于世界地图的实时协作像素艺术平台' },
      { name: 'SpaceX国际空间站对接模拟器', url: 'https://iss-sim.spacex.com', desc: 'SpaceX官方推出的国际空间站对接模拟' },
      { name: 'Slow Roads - 无尽驾驶模拟器', url: 'https://slowroads.io', desc: 'Slow Roads是一款基于浏览器的无' },
      { name: 'bloxd.io - 免费在线沙盒建造游戏', url: 'https://bloxd.io/', desc: 'bloxd.io是一款创新的多人在线沙盒' },
      { name: 'Yorg.io', url: 'https://www.yorg.io/', desc: 'Yorg.io是一款免费的在线塔防策略游' },
      { name: 'Paper Games', url: 'https://papergames.io', desc: '一个提供多种纸笔游戏的在线平台' },
      { name: 'MK48.io', url: 'https://mk48.io', desc: 'MK48.io是一个免费的多人在线海战游' },
      { name: 'Neave互动网页实验室', url: 'https://neave.com/', desc: 'Neave.com是一个集合了多种创意互' },
      { name: '共和国之辉', url: 'https://www.gongheguozhihui.com/', desc: '一款基于WebGL技术的红色警戒2网页版' },
      { name: '神庙逃亡在线版', url: 'https://tr.heheda.top/', desc: '一个无需下载的在线神庙逃亡游戏平台' }
    ],
  },
  {
    id: 'explore-map',
    name: '地理漫游',
    desc: '街景、地图与太空探索',
    icon: 'compass',
    links: [
      { name: 'MiniTokyo3D', url: 'https://minitokyo3d.com/', desc: '一个展示东京地铁实时运行状况的3D可视化' },
      { name: 'CTBUH - 世界高层建筑与都市人居协会', url: 'https://www.ctbuh.org', desc: 'CTBUH是全球领先的高层建筑和城市人居' },
      { name: 'RocketLaunch', url: 'https://rocketlaunch.org/', desc: '一个专业的火箭发射信息追踪平台' },
      { name: 'Time.is', url: 'https://time.is', desc: 'Time.is是一个基于原子钟的精确时间' },
      { name: 'Light Pollution Map', url: 'https://www.lightpollutionmap.info', desc: '一个专业的全球光污染可视化地图平台' },
      { name: 'SkylineWebcams', url: 'https://www.skylinewebcams.com', desc: '全球实时风景摄像头聚合平台' },
      { name: 'Plane Crash Info', url: 'http://www.planecrashinfo.com/lastwords.htm', desc: '这是一个专业的航空事故数据库' },
      { name: 'FindStarlink - 实时追踪星链卫星过境时间与位置', url: 'https://findstarlink.com', desc: 'FindStarlink是一个专为天文爱' },
      { name: '中国历史地图集 - 在线历史地理信息系统', url: 'https://www.ageeye.cn', desc: 'AgeEye是一个专注于中国历史地理信息' },
      { name: 'Windy - 全球交互式气象预报平台', url: 'https://www.windy.com', desc: 'Windy是一款基于高精度气象数据的全球' },
      { name: 'Chrome星星实验：银河系3D可视化探索', url: 'http://stars.chromeexperiments.com', desc: 'Chrome Experiments推出' },
      { name: '指尖上', url: 'https://www.zhijianshang.com/', desc: '一个提供全球各地360度全景VR观光体验' },
      { name: '地球时间线 | 可视化地球历史与生命演化', url: 'https://timelineofearth.com', desc: '该网站通过交互式时间轴可视化地球46亿年' }
    ],
  },
  {
    id: 'culture',
    name: '艺术人文',
    desc: '名画、音乐与文化馆藏',
    icon: 'palette',
    links: [
      { name: 'Public Pianos', url: 'https://pianos.pub/', desc: '全球公共钢琴查找平台' },
      { name: 'BeddySongs', url: 'https://beddysongs.com/', desc: '全球儿歌精选平台' },
      { name: 'Standard Guitar', url: 'https://www.standardguitar.com', desc: 'Standard Guitar是一个专业' },
      { name: '音乐圣经', url: 'https://www.musicbible.com', desc: 'MusicBible是一个专注于音乐历史' },
      { name: 'Virtual Piano', url: 'https://virtualpiano.net/music-sheets', desc: 'Virtual Piano是一个在线虚拟' },
      { name: 'SoundHound', url: 'https://www.soundhound.com', desc: 'SoundHound是一个集音乐识别、语' },
      { name: 'Public Domain Review', url: 'https://publicdomainreview.org', desc: '一个专注于展示和探索公共领域文化遗产的数' },
      { name: 'Autopiano - 在线钢琴模拟器', url: 'https://www.autopiano.cn/', desc: 'Autopiano是一个免费的在线钢琴模' },
      { name: '在线钢琴模拟器', url: 'https://www.xiwnn.com/piano/', desc: '一个基于Web的虚拟钢琴模拟器' },
      { name: '世界各国国歌在线播放与歌词库', url: 'http://anthems.lidicity.com', desc: 'Anthems.lidicity.com' },
      { name: 'Altered Qualia - 创意编程与WebGL实验展示平台', url: 'https://alteredqualia.com', desc: 'Altered Qualia是由开发者F' },
      { name: '与专业人士对话 - 职业访谈与行业洞察平台', url: 'http://www.talkingwiththepros.com', desc: '与专业人士对话是一个专注于职业访谈和行业' },
      { name: 'Gallerix亚洲-世界名画在线博物馆与艺术收藏库', url: 'https://gallerix.asia', desc: 'Gallerix.asia是一个专注于世' },
      { name: 'WikiArt', url: 'https://www.wikiart.org', desc: 'WikiArt是全球最大的在线艺术百科全' },
      { name: 'TuneIn - 全球广播电台与播客平台', url: 'http://tunein.com', desc: 'TuneIn是全球领先的音频流媒体服务平' },
      { name: 'Happy - 在线音乐播放器', url: 'https://happy.alang.run/', desc: 'Happy是一个简洁优雅的在线音乐播放器' },
      { name: '故宫博物院全景导览', url: 'https://pano.dpm.org.cn', desc: '故宫博物院全景导览系统提供紫禁城线上虚拟' },
      { name: 'Generative.fm - 人工智能生成环境音乐平台', url: 'https://generative.fm/', desc: 'Generative.fm是一个基于人工' },
      { name: 'Ice Alaska Photos', url: 'https://www.icealaskaphotos.com/', desc: 'Ice Alaska Photos是一个' },
      { name: 'XSList', url: 'https://xslist.org/', desc: 'XSList是一个专注于日本成人影片女演' }
    ],
  },
  {
    id: 'curio-tool',
    name: '冷门妙用',
    desc: '小众但顺手的实用站',
    icon: 'sparkles',
    links: [
      { name: 'AiSweet创建AI 女友互动的平台，通过聊天、视觉和语音。', url: 'https://aisweet.ai', desc: 'AiSweet是一个提供 AI 女友体验' },
      { name: '全球海底光缆3D地图', url: 'https://he.net/3d-map/', desc: '一个交互式3D地球可视化工具' },
      { name: 'Webcamtaxi', url: 'https://www.webcamtaxi.com/en/', desc: '全球实时网络摄像头直播平台' },
      { name: 'Vertébrés 3D', url: 'https://www.vertebres3d.fr/', desc: '一个提供脊椎动物骨骼3D模型的在线平台' },
      { name: 'Checkiday', url: 'https://www.checkiday.com/', desc: '一个全面的节日查询网站' },
      { name: 'Chinese New Year', url: 'https://chinesenewyear.net/', desc: '专业的农历新年信息门户网站' },
      { name: 'HistoricalTemperature - 历史气温数据查询', url: 'https://historicaltemperature.org/', desc: '专业的全球历史气温数据查询和分析平台' },
      { name: 'zi.tools 字统网', url: 'https://zi.tools/', desc: '一个专业的汉字综合查询工具' },
      { name: 'CoolCarsInChina', url: 'https://www.coolcarsinchina.com/', desc: '一个专注于中国汽车市场的英文资讯网站' },
      { name: 'Streetmix', url: 'https://streetmix.net', desc: '一个免费的在线街道设计工具' },
      { name: 'CMD在线命令行模拟器', url: 'https://www.cmd.to', desc: '一个基于浏览器的在线命令行学习工具' },
      { name: 'WebGradients', url: 'https://webgradients.com', desc: 'WebGradients提供180个精心' },
      { name: '贝塞尔曲线交互式学习与练习工具', url: 'http://bezier.method.ac/', desc: 'Bezier.method.ac是一个专' },
      { name: 'Mosh Pro', url: 'https://moshpro.app', desc: 'Mosh Pro是一款专业的视频后期处理' },
      { name: 'SVG Backgrounds', url: 'https://www.svgbackgrounds.com', desc: '一个提供免费、高质量SVG背景图案的在线' },
      { name: 'Easy Drawing Tutorials', url: 'https://www.easydrawingtutorials.com', desc: '一个免费的在线简笔画教学网站' },
      { name: 'Ringtone Maker', url: 'https://ringtonemaker.com', desc: '一款专业的在线铃声制作工具' },
      { name: 'wikiHow', url: 'https://www.wikihow.com', desc: 'wikiHow是一个全球性的实用技能指南' },
      { name: 'Top50Names', url: 'https://www.top50names.com', desc: '专业的名字排名和趋势分析工具' },
      { name: '年度幻觉奖官网 | 视错觉作品评选与展示平台', url: 'http://illusionoftheyear.com', desc: '年度幻觉奖官网（Illusion of ' },
      { name: '网页设计博物馆 - 探索互联网设计历史', url: 'https://www.webdesignmuseum.org', desc: '网页设计博物馆是一个数字化档案馆' },
      { name: 'RealBanknotes - 全球真实纸币收藏与交易平台', url: 'https://www.realbanknotes.com', desc: 'RealBanknotes是全球领先的纸' },
      { name: '天空之城 - 全球航拍社区和摄影作品分享平台', url: 'https://www.skypixel.com', desc: '天空之城（Skypixel）是大疆创新旗' },
      { name: '字帖生成器', url: 'https://xgzb.top/', desc: '一个挺实在的字帖生成网站' },
      { name: '食物派 - 专业食品成分查询与营养分析平台', url: 'https://www.foodwake.cn', desc: '食物派是一个专业的食品成分查询与营养分析' },
      { name: '世界数字图书馆 - 免费访问全球文化遗产', url: 'https://www.wdl.org', desc: '世界数字图书馆（WDL）由联合国教科文组' },
      { name: 'Zygote Body - 3D交互式人体解剖学探索平台', url: 'https://www.zygotebody.com', desc: 'Zygote Body提供基于WebGL' },
      { name: 'CosDNA化妆品成分查询分析平台', url: 'http://www.cosdna.com/', desc: 'CosDNA是一个专业的化妆品成分分析网' },
      { name: 'envisioningchemistry | 化学可视化科普平台', url: 'https://www.envisioningchemistry.cn', desc: 'envisioningchemistry' },
      { name: 'Fold &#039;N Fly - 纸飞机折叠指南大全', url: 'https://www.foldnfly.com', desc: 'Fold &#039' },
      { name: 'PhET互动模拟：免费物理化学在线科学和数学学习工具', url: 'https://phet.colorado.edu', desc: 'PhET是科罗拉多大学提供的免费互动模拟' },
      { name: '10分钟邮箱-临时邮箱地址生成工具', url: 'https://10minutEmail.com', desc: '10MinuteEmail提供免费的临时' },
      { name: '呼吸地球 - 全球实时人口与碳排放可视化', url: 'http://www.breathingearth.net', desc: 'Breathingearth是一个以动态' },
      { name: 'LifeSaver - 互动式急救培训平台', url: 'https://life-saver.org.uk', desc: 'LifeSaver是一款创新的互动式急救' },
      { name: 'A Soft Murmur - 环境白噪音生成器', url: 'http://asoftmurmur.com', desc: 'A Soft Murmur 是一个提供可' },
      { name: 'Linggle英语语法与搭配查询工具', url: 'http://www.linggle.com', desc: 'Linggle是一款基于自然语言处理技术' },
      { name: 'FindArticles - 学术文章与期刊资源搜索引擎', url: 'http://www.findarticles.com', desc: 'FindArticles是一个专注于聚合' },
      { name: '头态', url: 'https://toutai.cc', desc: '头态是一个专业的AI头像生成工具' },
      { name: 'Poetry Strands', url: 'https://poetrystrands.com', desc: 'Poetry Strands是一个专注于' },
      { name: 'Cherry AI', url: 'https://www.cherry-ai.com/', desc: 'Cherry AI是一个基于人工智能的创' },
      { name: 'KeepTrack', url: 'https://app.keeptrack.space/', desc: '一个实时卫星轨道追踪和可视化工具' },
      { name: '通辽宇宙', url: 'https://www.tongliaouniverse.cn/', desc: '通辽宇宙是一个充满恶搞和娱乐的网站' },
      { name: 'Ptable互动式元素周期表', url: 'https://ptable.com', desc: 'Ptable是一个功能强大的互动式元素周' },
      { name: '大型历史研究可视化', url: 'https://calculatingempires.net/', desc: 'Calculating Empires是' }
    ],
  },

